src/main/java/com/br/estimativadeprojetodesoftware/model/Estimativa.java, src/main/java/com/br/estimativadeprojetodesoftware/model/Perfil.java, src/main/java/com/br/estimativadeprojetodesoftware/model/Usuario.java
=> Refatoração da Model

pom.xml, src/main/java/com/br/estimativadeprojetosoftware/view/DashBoardProjetoView.java, src/main/java/com/br/estimativadeprojetosoftware/view/DetalheProjetoView.java, src/main/java/com/br/estimativadeprojetosoftware/view/GlobalWindowManager.java, src/main/java/com/br/estimativadeprojetosoftware/view/PrincipalView.java
=> Lançamento da view

src/main/java/com/br/estimativadeprojetodesoftware/view/DashBoardProjetoView.java, src/main/java/com/br/estimativadeprojetodesoftware/view/DetalheProjetoView.java, src/main/java/com/br/estimativadeprojetodesoftware/view/GlobalWindowManager.java, src/main/java/com/br/estimativadeprojetodesoftware/view/PrincipalView.java
=> Renomeando pacote view

src/main/java/com/br/estimativadeprojetodesoftware/presenter/DashBoardProjetoPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/DesktopMemento.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/DetalheProjetoPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/Observer.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/PrincipalPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/Zelador.java
=> Lançamento da presenter

src/main/java/com/br/estimativadeprojetodesoftware/repository/ProjetoRepositoryMock.java
=> Lançamento da repository

src/main/java/com/br/estimativadeprojetodesoftware/presenter/DashBoardProjetoPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/DetalheProjetoPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/PrincipalPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/service/ComponenteNoArvore.java, src/main/java/com/br/estimativadeprojetodesoftware/service/ConstrutorDeArvoreNavegacaoService.java, src/main/java/com/br/estimativadeprojetodesoftware/service/CriarBarraBotaoService.java, src/main/java/com/br/estimativadeprojetodesoftware/service/CriarProjetoMock.java, src/main/java/com/br/estimativadeprojetodesoftware/service/EstimaProjetoService.java, src/main/java/com/br/estimativadeprojetodesoftware/service/IconService.java, src/main/java/com/br/estimativadeprojetodesoftware/service/NoArvoreComposite.java, src/main/java/com/br/estimativadeprojetodesoftware/service/ProvedorMenuContextual.java
=> Lançamento da service

src/main/java/com/br/estimativadeprojetodesoftware/command/AbrirDashboardProjetoCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/command/AbrirDetalhesProjetoProjetoCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/command/AbrirInternalFrameGenericoProjetoCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/command/CriarProjetoProjetoCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/command/ExcluirProjetoProjetoCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/command/MostrarMensagemProjetoCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/command/ProjetoCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/PrincipalPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/service/CriarBarraBotaoService.java
=> Lançamento do command

src/main/java/com/br/estimativadeprojetodesoftware/presenter/DashBoardProjetoPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/DetalheProjetoPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/Observer.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/PrincipalPresenter.java
Refatoração da presenter para fazer alguns ajustes
=> Refatoração da presenter para fazer alguns ajustes

src/main/java/com/br/estimativadeprojetodesoftware/model/Subject.java
=> Refatoração da model pt 4

src/main/java/com/br/estimativadeprojetodesoftware/model/Projeto.java
Refatoração da model na classe projeto
=> Refatoração da model na classe projeto

src/main/java/com/br/estimativadeprojetodesoftware/command/CriarProjetoProjetoCommand.java
=> Refatoração da command

src/main/java/com/br/estimativadeprojetodesoftware/presenter/DetalheProjetoPresenter.java
=> Refatoração da presenter

src/main/java/com/br/estimativadeprojetodesoftware/repository/ProjetoRepositoryMock.java
=> Refatoração da repository

src/main/java/com/br/estimativadeprojetodesoftware/presenter/DashBoardProjetoPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/DetalheProjetoPresenter.java
=> Refatoração da presenter pt 2

src/main/java/com/br/estimativadeprojetodesoftware/service/CriarProjetoMock.java, src/main/java/com/br/estimativadeprojetodesoftware/service/EstimaProjetoService.java
=> Refatoração da service

src/main/java/com/br/estimativadeprojetodesoftware/model/Projeto.java
=> Refatoração da model pt 5

src/main/java/com/br/estimativadeprojetodesoftware/service/CriarProjetoMock.java
=> Refatoração da service pt 2

src/main/java/com/br/estimativadeprojetodesoftware/repository/ProjetoRepositoryMock.java
Refatoração da repository, alterando classe nos metódos adicionarProjeto e Construtor
=> Refatoração da repository, alterando classe nos metódos

src/main/java/com/br/estimativadeprojetodesoftware/command/CriarProjetoProjetoCommand.java
Correção da classe CriarProjetoCommand
=> Correção da classe CriarProjetoCommand

src/main/java/com/br/estimativadeprojetodesoftware/presenter/helpers/WindowManager.java, src/main/java/com/br/estimativadeprojetodesoftware/principal/Principal.java
=> Lançamento da helpers

src/main/java/com/br/estimativadeprojetodesoftware/presenter/PrincipalPresenter.java
Refatoração da classe PrincipalPresenter
=> Refatoração da classe PrincipalPresenter

src/main/java/com/br/estimativadeprojetodesoftware/command/AbrirDashboardProjetoCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/command/AbrirDetalhesProjetoProjetoCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/command/AbrirInternalFrameGenericoProjetoCommand.java
Refatoração do command para se adequar WindowManager
=> Refatoração do command para se adequar WindowManager

src/main/java/com/br/estimativadeprojetodesoftware/presenter/LoginPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/view/PrincipalView.java
Adicionando na presenter a classe LoginPresenter
=> Adicionando na presenter a classe LoginPresenter

src/main/java/com/br/estimativadeprojetodesoftware/repository/UsuarioRepositoryMock.java
Lançamento do UsuarioRepositoryMock
=> Lançamento do UsuarioRepositoryMock

pom.xml, src/main/java/com/br/estimativadeprojetodesoftware/presenter/LoginPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/PrincipalPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/principal/Principal.java
Refatoração da principal e login presenter
=> Refatoração da principal e login presenter

src/main/java/com/br/estimativadeprojetodesoftware/service/CriarProjetoMock.java
Refatoração e correção da service
=> Refatoração e correção da service

src/main/java/com/br/estimativadeprojetodesoftware/presenter/LoginPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/PrincipalPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/principal/Principal.java
Refatorando a presenter para login e cadastro
=> Refatorando a presenter para login e cadastro

src/main/java/com/br/estimativadeprojetodesoftware/command/AbrirLoginUsuarioCommand.java
Lançamento do command de login
=> Lançamento do command de login

src/main/java/com/br/estimativadeprojetodesoftware/presenter/LoginPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/PrincipalPresenter.java
Refatoração da classe LoginPresenter
=> Refatoração da classe LoginPresenter

src/main/java/com/br/estimativadeprojetodesoftware/command/AbrirLoginUsuarioCommand.java
Refatoração da classe AbrirLoginUsuarioCommand
=> Refatoração da classe AbrirLoginUsuarioCommand

src/main/java/com/br/estimativadeprojetodesoftware/presenter/PrincipalPresenter.java
Refatoração da PrincipalPresenter pt 2
=> Refatoração da PrincipalPresenter pt 2

src/main/java/com/br/estimativadeprojetodesoftware/presenter/window_command/ConfigurarViewCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/principal/Principal.java
Refatoração da configuração da view command
=> Refatoração da configuração da view command

src/main/java/com/br/estimativadeprojetodesoftware/presenter/window_command/ConfigurarViewCommand.java
Mais uma refatoração da config da view
=> Mais uma refatoração da config da view

src/main/java/com/br/estimativadeprojetodesoftware/command/AbrirLoginUsuarioCommand.java
Refatoração command para Login
=> Refatoração command para Login

src/main/java/com/br/estimativadeprojetodesoftware/presenter/PrincipalPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/principal/Principal.java
Removendo a parte de login na principal presenter
=> Removendo a parte de login na principal presenter

src/main/java/com/br/estimativadeprojetodesoftware/presenter/window_command/ConfigurarViewCommand.java
Removendo a chamada de command principal de login
=> Removendo a chamada de command principal de login

src/main/java/com/br/estimativadeprojetodesoftware/model/Perfil.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/DetalheProjetoPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/ProjetoRepositoryMock.java
problema resolvido de não exibir valores dos campos. A solução foi vincular os perfis aos projetos
=> Repository

src/main/java/com/br/estimativadeprojetodesoftware/command/AbrirLoginUsuarioCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/DashBoardProjetoPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/DetalheProjetoPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/LoginPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/Observer.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/PrincipalPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/window_command/ConfigurarMenuJanelaCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/window_command/ConfigurarViewCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/principal/Principal.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/ProjetoRepositoryMock.java, src/main/java/com/br/estimativadeprojetodesoftware/service/ConstrutorDeArvoreNavegacaoService.java, src/main/java/com/br/estimativadeprojetodesoftware/service/CriarBarraService.java, src/main/java/com/br/estimativadeprojetodesoftware/singleton/UsuarioLogadoSingleton.java, src/main/java/com/br/estimativadeprojetodesoftware/view/LoginView.form, src/main/java/com/br/estimativadeprojetodesoftware/view/LoginView.java
=> Lançamento do módulo de login

src/main/java/com/br/estimativadeprojetodesoftware/service/CriarBarraService.java
Refatoração para exibir nome do usuario logado
=> Refatoração para exibir nome do usuario logado

pom.xml, src/main/java/com/br/estimativadeprojetodesoftware/adapter/ValidadorSenhaAdapter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/CadastroPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/LoginPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/principal/Principal.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/UsuarioRepositoryMock.java, src/main/java/com/br/estimativadeprojetodesoftware/service/ValidadorSenhaService.java, src/main/java/com/br/estimativadeprojetodesoftware/view/CadastroView.form, src/main/java/com/br/estimativadeprojetodesoftware/view/CadastroView.java, src/main/java/com/br/estimativadeprojetodesoftware/view/LoginView.form, src/main/java/com/br/estimativadeprojetodesoftware/view/LoginView.java
Lançamento do cadastro de usuario
=> Lançamento do cadastro de usuario

src/main/java/com/br/estimativadeprojetodesoftware/command/EditarUsuarioCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/command/ExcluirUsuarioCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/command/LogoutCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/command/SalvarUsuarioCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/command/UsuarioCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/model/Usuario.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/CadastroPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/PrincipalPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/UsuarioPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/window_command/ConfigurarMenuJanelaCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/principal/Principal.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/UsuarioRepositoryMock.java, src/main/java/com/br/estimativadeprojetodesoftware/service/CriarBarraService.java, src/main/java/com/br/estimativadeprojetodesoftware/service/ValidadorSenhaService.java, src/main/java/com/br/estimativadeprojetodesoftware/state/EdicaoState.java, src/main/java/com/br/estimativadeprojetodesoftware/state/UsuarioPresenterState.java, src/main/java/com/br/estimativadeprojetodesoftware/state/VisualizacaoState.java, src/main/java/com/br/estimativadeprojetodesoftware/view/UsuarioView.form, src/main/java/com/br/estimativadeprojetodesoftware/view/UsuarioView.java
Lançamento da state e modulo de visualização de usuário
=> Lançamento da state e modulo de visualização de usuário

src/main/java/com/br/estimativadeprojetodesoftware/presenter/CadastroProjetoPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/view/CadastroProjetoView.form, src/main/java/com/br/estimativadeprojetodesoftware/view/CadastroProjetoView.java
=> Criando cadastro de projeto

src/main/java/com/br/estimativadeprojetodesoftware/command/AbrirCompartilhamentoProjetoCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/command/CompartilharProjetoCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/CompartilharProjetoPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/PrincipalPresenter.java
Refatoração da funcionalidade compartilhar projeto
=> Refatoração da funcionalidade compartilhar projeto

src/main/java/com/br/estimativadeprojetodesoftware/command/AbrirCompartilhamentoProjetoCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/command/AbrirDashboardProjetoCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/command/AbrirDetalhesProjetoProjetoCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/command/AbrirPrincipalPresenterCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/command/projeto/AbrirCriarProjetoCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/command/projeto/AbrirEdicaoProjetoCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/command/projeto/ExcluirProjetoCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/command/usuario/LogoutCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/command/usuario/ManterUsuarioCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/model/Projeto.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/helpers/WindowManager.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/projeto/CompartilharProjetoPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/projeto/DashBoardProjetoPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/projeto/DetalheProjetoPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/projeto/EdicaoProjetoPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/projeto/PrincipalPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/window_command/AtualizarViewCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/window_command/ConfigurarMenuJanelaCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/window_command/ConfigurarViewCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/window_command/FecharTodasJanelasCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/ProjetoRepositoryMock.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/UsuarioRepositoryMock.java, src/main/java/com/br/estimativadeprojetodesoftware/service/CriarProjetoMock.java, src/main/java/com/br/estimativadeprojetodesoftware/service/DataHoraService.java, src/main/java/com/br/estimativadeprojetodesoftware/view/projeto/EdicaoProjetoView.form, src/main/java/com/br/estimativadeprojetodesoftware/view/projeto/EdicaoProjetoView.java
Refatoração criação e edição de projeto
=> Refatoração criação e edição de projeto

src/main/java/com/br/estimativadeprojetodesoftware/model/Perfil.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/projeto/DetalheProjetoPresenter.java
=> atualização da model

src/main/java/com/br/estimativadeprojetodesoftware/model/Campo.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/projeto/CadastroProjetoPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/projeto/DetalheProjetoPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/projeto/EdicaoProjetoPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/ICampoRepository.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/ProjetoRepositoryMock.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/h2/CampoRepositoryH2.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/h2/PerfilRepositoryH2.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/h2/ProjetoRepositoryH2.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/h2/UsuarioRepositoryH2.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/sqlite/CampoRepositorySQLite.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/sqlite/PerfilRepositorySQLite.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/sqlite/ProjetoRepositorySQLite.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/sqlite/UsuarioRepositorySQLite.java, src/main/java/com/br/estimativadeprojetodesoftware/service/CampoRepositoryService.java, src/main/java/com/br/estimativadeprojetodesoftware/service/CriarProjetoMock.java
Refatoração da repository, base inicial completa
=> Refatoração da repository, base inicial completa

src/main/java/com/br/estimativadeprojetodesoftware/command/usuario/ExcluirUsuarioCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/command/usuario/SalvarUsuarioCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/usuario/CadastroPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/usuario/LoginPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/usuario/ManterUsuarioPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/usuario/PrincipalUsuarioPresenter.java
Refatoração de login e cadastro com repository real
=> Refatoração de login e cadastro com repository real

src/main/java/com/br/estimativadeprojetodesoftware/command/usuario/ExcluirUsuarioCommand.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/ICampoRepository.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/IUsuarioRepository.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/h2/CampoRepositoryH2.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/h2/UsuarioRepositoryH2.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/sqlite/CampoRepositorySQLite.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/sqlite/PerfilRepositorySQLite.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/sqlite/ProjetoRepositorySQLite.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/sqlite/UsuarioRepositorySQLite.java, src/main/java/com/br/estimativadeprojetodesoftware/service/CampoRepositoryService.java, src/main/java/com/br/estimativadeprojetodesoftware/service/UsuarioRepositoryService.java, src/main/java/com/br/estimativadeprojetodesoftware/singleton/ConexaoSingleton.java
Atualizações na Repository (Campo)
=> Atualizações na Repository (Campo)

.env, src/main/java/com/br/estimativadeprojetodesoftware/abstractfactory/SeletorFabricaRepository.java, src/main/java/com/br/estimativadeprojetodesoftware/principal/Principal.java
=> Atualização .env e principal

src/main/java/com/br/estimativadeprojetodesoftware/presenter/perfil/PerfilProjetoPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/presenter/usuario/LoginPresenter.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/IPerfilRepository.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/h2/PerfilRepositoryH2.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/h2/ProjetoRepositoryH2.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/h2/UsuarioRepositoryH2.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/sqlite/PerfilRepositorySQLite.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/sqlite/ProjetoRepositorySQLite.java, src/main/java/com/br/estimativadeprojetodesoftware/repository/sqlite/UsuarioRepositorySQLite.java, src/main/java/com/br/estimativadeprojetodesoftware/service/AutenticacaoService.java, src/main/java/com/br/estimativadeprojetodesoftware/service/CampoRepositoryService.java, src/main/java/com/br/estimativadeprojetodesoftware/service/PerfilRepositoryService.java, src/main/java/com/br/estimativadeprojetodesoftware/service/ProjetoRepositoryService.java
Atualização repository e autenticação de login
=> Atualização repository e autenticação de login
